[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
stdout_logfile=/var/log/supervisor/nginx.log
stderr_logfile=/var/log/supervisor/nginx.log
autorestart=true
priority=10

[program:server]
command=python3 /app/main.py
directory=/app
stdout_logfile=/var/log/supervisor/server.log
stderr_logfile=/var/log/supervisor/server.log
autorestart=true
priority=20
